Update the sqlalchemy
juwai/zask pull request #17
Opened 2017-07-13 05:56 UTC by zhangjustin

1. Removed unused import.
2. Update the sqlalchemy version control.
3. Update the zask version to 1.9.5.

Test:
1. Run the unittest

2017-07-13 09:40 UTC, tjoelsson requested changes

2017-07-13 09:40 UTC, tjoelsson commented on setup.py
>          'zerorpc==0.5.1',
Can you also change this to: `zerorpc>=0.5.1, <0.7`?

2017-07-13 09:40 UTC, tjoelsson commented on CHANGES
> +released on July 13th 2017
Empty line above this one

2017-07-13 09:40 UTC, tjoelsson commented on CHANGES
> +* Update SQLAlchemy to the version 1.1.11
Allow SQLAlchemy up to version 1.1

2017-07-13 09:40 UTC, tjoelsson commented on tests/test_sqlalchemy.py
> +
Why separate unittest from other builtin libraries?

2017-07-13 10:04 UTC, zhangjustin commented
updated, please review.

2017-07-13 10:12 UTC, tjoelsson requested changes

2017-07-13 10:12 UTC, tjoelsson commented on tests/test_sqlalchemy.py
> +from datetime import datetime
put together with other builtin packages above

2017-07-13 10:12 UTC, tjoelsson commented on CHANGES
Allow ZeroRPC up to version 0.6

2017-07-13 10:17 UTC, zhangjustin commented on tests/test_sqlalchemy.py
> +from datetime import datetime
sorry, forget that datetime is builtin package

2017-07-13 10:20 UTC, zhangjustin commented
Updated, please review.

2017-07-14 02:53 UTC, tjoelsson approved these changes

2017-07-14 02:53 UTC, tjoelsson commented on tests/test_sqlalchemy.py
>  from datetime import datetime
? order alphabetically

2017-07-14 04:07 UTC, mark-juwai approved these changes

2017-07-14 04:10 UTC, tjoelsson approved these changes

2017-07-14 07:47 UTC, zhangjustin commented
Merge

2017-07-14 07:47 UTC, merged